<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BtsLiveTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('bts_live')->delete();
        
        \DB::table('bts_live')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'youtube_id' => '5eqafhAMVVY',
                'judul' => 'testing',
                'tanggal' => '2023-10-22',
                'cover' => 'AWWzho0YL5sQx6S0BZEEVFIn3T6a4sk0nUyg5Btn.jpg',
                'episode' => 1,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-10-22 18:29:32',
                'updated_at' => '2023-10-22 18:29:32',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 1,
                'youtube_id' => 'l7dSBlnt4cY',
                'judul' => 'Potensi Desa Wisata Organik',
                'tanggal' => '2023-11-14',
                'cover' => '0qVOCra6JakGUeqbXMHo0lvdJjYDkMUApStTnLhO.jpg',
                'episode' => 1043,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-11-14 11:04:47',
                'updated_at' => '2023-11-14 11:12:09',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 1,
                'youtube_id' => 'SiU9I7FrZu0',
                'judul' => 'UMKM Ramah Lingkungan menuju Go Eksport',
                'tanggal' => '2023-11-15',
                'cover' => 'VN0V99Mv2JCR0OaFRuuIVuNi9iaipZ3qkOnhJn6X.jpg',
                'episode' => 1044,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-11-15 09:40:24',
                'updated_at' => '2023-11-15 09:40:24',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 1,
                'youtube_id' => 'UKAzsJ_Chmw',
                'judul' => 'Analisis Usaha Tani yang Prospektif dalam Rangka Menjaga Ketahanan Pangan Nasional Menuju Indonesia Emas Tahun 2045',
                'tanggal' => '2023-11-16',
                'cover' => 'ukOVQsSKoQJlmKVnGw6CoCktXNqVNmxmqUXFt0K6.jpg',
                'episode' => 1045,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-11-16 09:49:20',
                'updated_at' => '2023-11-16 09:49:20',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 1,
                'youtube_id' => 'WCSwWSHFkSI',
                'judul' => 'Mekanisme Perlindungan Varietas Tanaman, Pendaftaran Varietas Lokal & Hasil Pemuliaan, dan Pendaftaran Pupuk Organik',
                'tanggal' => '2023-11-20',
                'cover' => '6Pbi2hYRblBcqCvig6eFuLK3fC6R951aNepsbrBz.jpg',
                'episode' => 1047,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-11-20 11:04:57',
                'updated_at' => '2023-11-20 11:04:57',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 1,
                'youtube_id' => 'nrkZbM2Mo9c',
                'judul' => 'Antisipasi Serangan Penyakit',
                'tanggal' => '2023-11-21',
                'cover' => 'KstERTASxZNB4KmrEiLeGQsbkOyS0aK15A52MWFN.jpg',
                'episode' => 1048,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-11-21 14:19:27',
                'updated_at' => '2023-11-21 14:19:27',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 1,
                'youtube_id' => 'sApf5wSA5dQ',
                'judul' => 'Memperkuat Ketahanan Pangan Lokal Provinsi Sulawesi Tengah sebagai Penyangga Pangan IKN',
                'tanggal' => '2023-11-22',
                'cover' => 'yfSIJXEtgiVITuraJzhH5wlJYEHrkPYtaadGGfbG.jpg',
                'episode' => 1049,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-11-22 09:41:34',
                'updated_at' => '2023-11-22 09:41:34',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 1,
                'youtube_id' => 'd6r_kMhxI0g',
                'judul' => 'Pengaruh Variabel Iklim Terhadap Produksi Tanaman Pangan',
                'tanggal' => '2023-11-23',
                'cover' => '8tUaulWAGZ5zFfEmKwvZPG3mOjgn17TMHAfa2ul9.jpg',
                'episode' => 1050,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-11-23 10:07:40',
                'updated_at' => '2023-11-23 10:07:40',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 1,
                'youtube_id' => 'jdD1b43VkGU',
                'judul' => 'Urgensi PPL Menyukseskan Menanam Padi Rawa',
                'tanggal' => '2023-11-27',
                'cover' => 'kTxFfF80n77WO29fG6lL4YXeoIDgrgcnbDSkVEiE.jpg',
                'episode' => 1051,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-11-27 11:01:49',
                'updated_at' => '2023-11-27 11:24:13',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 1,
                'youtube_id' => 'ovOQTox6pOs',
                'judul' => 'Biosaka : Aplikasi Pertanian Ramah Lingkungan',
                'tanggal' => '2023-11-28',
                'cover' => 'BskKFxhiDBKtie2feJ8MqjUy2Q5gxI8bdcy85m9g.jpg',
                'episode' => 1052,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-11-28 20:52:33',
                'updated_at' => '2023-11-28 20:52:33',
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 1,
                'youtube_id' => 'eDtYUR44BRA',
                'judul' => 'Maksimalkan Potensi Lahan Rawa untuk Tanaman Pangan',
                'tanggal' => '2023-11-29',
                'cover' => 'fe2Ksi774c2WoJx97QhgLg7Nk8JYFMO5QHISN53L.jpg',
                'episode' => 1053,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-11-29 09:25:18',
                'updated_at' => '2023-11-29 09:25:18',
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 1,
                'youtube_id' => '_OwHG2YS_20',
                'judul' => 'Urgensi Pengembangan Singkong sebagai Komoditas Strategis Nasional untuk Bahan Pangan, Pakan, dan Bioindustri',
                'tanggal' => '2023-11-30',
                'cover' => 'BR6Nt1tLbmdl06FSrBIlDSPy78WxidESYMH4eP7z.jpg',
                'episode' => 1054,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-11-30 11:03:21',
                'updated_at' => '2023-11-30 11:03:21',
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 1,
                'youtube_id' => 'Najs1HL7LxY',
                'judul' => 'Hilirisasi Pangan',
                'tanggal' => '2023-12-04',
                'cover' => 'AZ0J8EfJYCOTLxdCX7rqZdnLDU2TJXpt1DGr96ci.jpg',
                'episode' => 1055,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-04 09:26:57',
                'updated_at' => '2023-12-04 09:26:57',
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 1,
                'youtube_id' => 'KMw58zNEKrY',
                'judul' => 'Pemanfaatan Lahan Rawa dan  Gambut untuk Pertanian dan Perkebunan',
                'tanggal' => '2023-12-04',
                'cover' => 'C3YjEu2QYTfghuxWWZh2RWySkkpXpwbeJRXUQa1k.jpg',
                'episode' => 1056,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-04 13:14:11',
                'updated_at' => '2023-12-04 13:14:11',
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 1,
                'youtube_id' => 't4-ZYPLftLk',
                'judul' => 'Rekomendasi Tanaman Padi di Lahan Kering & Rawa',
                'tanggal' => '2023-12-05',
                'cover' => '2lb8IVwjlIYlK25Hr5QDYbfJQIbEMaHadx5sB7yZ.jpg',
                'episode' => 1057,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-05 09:13:43',
                'updated_at' => '2023-12-05 09:13:43',
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 1,
                'youtube_id' => 'os7xdIoAELc',
                'judul' => 'Percepatan Tanam dan Peningkatan Produksi',
                'tanggal' => '2023-12-06',
                'cover' => 'CC0f3h7MAARpEsbdxC6zf8idXWt9GyPj4RJprGXO.jpg',
                'episode' => 1058,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-06 09:04:57',
                'updated_at' => '2023-12-06 09:04:57',
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 1,
                'youtube_id' => 'v9iXZ2A_eSg',
                'judul' => 'Menumbuhkan Minat Penangkar Benih',
                'tanggal' => '2023-12-07',
                'cover' => 'vmAqgnGE2JsIhICY8iiTps70q6anFCfWPxRQyAnj.jpg',
                'episode' => 1059,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-07 09:17:23',
                'updated_at' => '2023-12-07 09:17:23',
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 1,
                'youtube_id' => 'Dz71uRcQuEg',
                'judul' => 'Strategi Lumbung Pangan Dunia "Indonesia Emas 2045"',
                'tanggal' => '2023-12-11',
                'cover' => '6pB3Knqg0IyWxFov7XmJnM9eP7SSkQx3jQ1BysnE.jpg',
                'episode' => 1060,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-11 13:45:48',
                'updated_at' => '2023-12-11 13:45:48',
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 1,
                'youtube_id' => 'D3oonDJaPH8',
                'judul' => 'Aneka Pangan Sehat untuk Menyambut Tahun Baru 2024',
                'tanggal' => '2023-12-12',
                'cover' => '0nFWiyEfRz18vglmL5IcfuyDRHKwseZadtT9exKl.jpg',
                'episode' => 1061,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-12 09:07:52',
                'updated_at' => '2023-12-12 09:07:52',
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 1,
                'youtube_id' => 'lXD0W37EBkA',
                'judul' => 'Prospek Bisnis Pertanian Organik yang Menggiurkan',
                'tanggal' => '2023-12-13',
                'cover' => 'RBTgOBnUF9o0bYHBUqjs8FZ714ADXNLISpS6FwzO.jpg',
                'episode' => 1062,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-13 09:11:31',
                'updated_at' => '2023-12-13 09:11:31',
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 1,
                'youtube_id' => 'H9QojlufSoo',
                'judul' => 'Kiat Sukses Pelaku Usaha Tani untuk Memperluas Bisnis & Meningkatkan Kesejahteraan Keluarga Menuju Terwujudnya Lumbung Pangan Dunia Tahun 2045',
                'tanggal' => '2023-12-14',
                'cover' => 'Qh4Iahw8S3pts8TVo7dgK8ZyW2lZq86Hbd7zpb7n.jpg',
                'episode' => 1063,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-14 09:30:12',
                'updated_at' => '2023-12-14 09:30:12',
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 1,
                'youtube_id' => 'kvf5EywdxQA',
                'judul' => 'Teknologi Pengolahan Tanaman Singkong',
                'tanggal' => '2023-12-18',
                'cover' => 'mcuCDFczcLvdRTjVkGltQFNoswuZHm66xA3TLiGY.jpg',
                'episode' => 1064,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-18 09:52:32',
                'updated_at' => '2023-12-18 09:52:32',
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 1,
                'youtube_id' => 'Knah__j2HmQ',
                'judul' => 'Resistensi WBC',
                'tanggal' => '2023-12-19',
                'cover' => 'eqkk87AmQX7UIPOBAsivOfvZPWmSSL0E75L9Aa6K.jpg',
                'episode' => 1065,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-19 09:05:39',
                'updated_at' => '2023-12-19 09:05:39',
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 1,
                'youtube_id' => 'Jc_s_WchFpY',
            'judul' => 'Kuatkan Gapoktan Kuat Pangan (Awasi Kontrol Monitoring secara Serius)',
                'tanggal' => '2023-12-20',
                'cover' => 'BcTsh3VmTx3q4LLLFvGBELUXxeY7ESs8aVXQufak.jpg',
                'episode' => 1066,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-20 09:09:31',
                'updated_at' => '2023-12-20 09:09:31',
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 1,
                'youtube_id' => 'UzlSoIJH6zQ',
            'judul' => 'Kemudahan Perizinan Berushaa Sub- Sektor Tanaman Pangan melalui Online Single Submission (OSS)',
                'tanggal' => '2023-12-21',
                'cover' => '4GuLeyl72KkLbtG0dyGoC4PNMAUDNZ2ts1NmU4VS.jpg',
                'episode' => 1067,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-21 09:07:25',
                'updated_at' => '2023-12-21 09:07:25',
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 1,
                'youtube_id' => '5fzq4iKV_wA',
                'judul' => 'Penanganan Banjir pada Tanaman Pangan MH 2023/2024',
                'tanggal' => '2023-12-21',
                'cover' => 'LoKVM860KT9ssVGaX01OUldxqPy64T7l5U551glt.jpg',
                'episode' => 1068,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-21 13:13:34',
                'updated_at' => '2023-12-21 13:13:34',
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 1,
                'youtube_id' => 'bFLmFgzjsQo',
                'judul' => 'Peran Ibu dalam Memilih Bahan Pangan untuk Program Stunting Mandiri',
                'tanggal' => '2023-12-22',
                'cover' => 'NPWHdQv6ml1zwAahMgYvR33HH8Xx1YPNVO3FcsnJ.jpg',
                'episode' => 1069,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-22 09:18:49',
                'updated_at' => '2023-12-22 09:18:49',
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 1,
                'youtube_id' => 'dPprWsaA31o',
                'judul' => 'Strategi Peningkatan Produksi Singkong Nasional',
                'tanggal' => '2023-12-27',
                'cover' => 'UlqluqdgRMDm9SUGZ1LAVzrGHv7CfCHDqx0qYSwN.png',
                'episode' => 1070,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-27 09:04:44',
                'updated_at' => '2023-12-27 09:04:44',
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 1,
                'youtube_id' => '-cvqXX40aE8',
                'judul' => 'Membina dan Menumbuhkan UMKM Pertanian',
                'tanggal' => '2023-12-28',
                'cover' => '0epHHvUeDftueb7REW5CJ8YQplE4ESrHgcEAoLCB.jpg',
                'episode' => 1071,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-28 09:06:18',
                'updated_at' => '2023-12-28 09:06:18',
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 1,
                'youtube_id' => 'HoO0XfdrKGE',
                'judul' => 'FGD Refleksi Akhir Tahun 2023 dan Outlook 2024: Potret dan Penguatan Produksi Padi untuk Memperkokoh Kedaulatan Pangan Nasional',
                'tanggal' => '2023-12-29',
                'cover' => 'fY4OT6yrnJIRM3TRjEbAvaIl2lthCV4OnXlU1V0Z.png',
                'episode' => 1072,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2023-12-29 14:37:47',
                'updated_at' => '2023-12-29 14:47:27',
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 1,
                'youtube_id' => 'CMIj2euvkLM',
                'judul' => 'Pemberdayaan Petani Jagung melalui Kegiatan Penanaman dan Pengolahan Produk Jagung yang Ramah Lingkungan',
                'tanggal' => '2024-01-02',
                'cover' => '4YrGNKQdgQIj8EjNbScOLUkwiROvKHUAPadMUxVt.jpg',
                'episode' => 1073,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-02 09:07:27',
                'updated_at' => '2024-01-02 09:07:27',
            ),
            31 => 
            array (
                'id' => 32,
                'user_id' => 1,
                'youtube_id' => 'J7-bC686GkU',
                'judul' => 'Penerapan Sistem Manajemen Terintegrasi untuk Jaminan Mutu Produk Pertanian',
                'tanggal' => '2024-01-08',
                'cover' => 'RbZgiT26mYFyquIaVtIFLskchnECl8WxDWhA5z2P.png',
                'episode' => 1076,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-08 09:08:28',
                'updated_at' => '2024-01-08 09:08:28',
            ),
            32 => 
            array (
                'id' => 33,
                'user_id' => 1,
                'youtube_id' => '0JrDrMB8AUI',
                'judul' => 'Pengembangan Kacang Tunggak di Lahan Marginal dan di Bawah Tanaman Jeruk',
                'tanggal' => '2024-01-09',
                'cover' => 'I4EXK4E6vJ4jtkDjMQ6GKSYMJxV5jeOn4YegYak7.jpg',
                'episode' => 1077,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-09 09:05:09',
                'updated_at' => '2024-01-09 09:05:09',
            ),
            33 => 
            array (
                'id' => 34,
                'user_id' => 1,
                'youtube_id' => 'JF6_w66lqek',
                'judul' => 'Pengendalian Hama Tikus Sawah',
                'tanggal' => '2024-01-10',
                'cover' => 'n8ZGRreE0o11TiczFWnmXEVlUhyu5Do3vyc2hYfh.jpg',
                'episode' => 1078,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-10 09:05:14',
                'updated_at' => '2024-01-10 09:05:14',
            ),
            34 => 
            array (
                'id' => 35,
                'user_id' => 1,
                'youtube_id' => 'cPU7OdMycdY',
                'judul' => 'Inovasi Teknologi Pengolahan Limbah Pertanian Tanaman Pangan yang Terkini & Tercanggih dalam Menghasilkan Pupuk Organik Berkualitas Super',
                'tanggal' => '2024-01-11',
                'cover' => 'sT054x5KXEB8F24EWDbDfBljFwIwRVRW6PL8aIVu.png',
                'episode' => 1079,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-11 11:04:50',
                'updated_at' => '2024-01-11 11:04:50',
            ),
            35 => 
            array (
                'id' => 36,
                'user_id' => 1,
                'youtube_id' => 'bHo4fll1S0k',
                'judul' => 'Tantangan MT1: Pengaruh El Nino Terhadap Peningkatan Produktivitas Tanaman',
                'tanggal' => '2024-01-11',
                'cover' => 'huDBBgfPiJ1kIqu6g4JDGOx6oEbLMiAprEYpXvOX.jpg',
                'episode' => 1080,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-11 13:09:57',
                'updated_at' => '2024-01-11 13:09:57',
            ),
            36 => 
            array (
                'id' => 37,
                'user_id' => 1,
                'youtube_id' => '2Cx68EJE7cM',
                'judul' => 'Burung Hantu Solusi Atasi Hama Tikus di Lahan Petani',
                'tanggal' => '2024-01-15',
                'cover' => 'DoBeaPRmZmcW4X0cGLMJLVrOH2XmfUrEQZMctqXV.jpg',
                'episode' => 1081,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-15 09:07:09',
                'updated_at' => '2024-01-15 09:07:09',
            ),
            37 => 
            array (
                'id' => 38,
                'user_id' => 1,
                'youtube_id' => 'E7zEdfDeBUE',
                'judul' => 'Bertani di Lahan Rawa Mineral dengan Dukungan Kearifan Lokal',
                'tanggal' => '2024-01-16',
                'cover' => 'rvGOURoISx9OAbsfbq4pciBXbmH7pqYv5rwnHmwU.jpg',
                'episode' => 1082,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-16 09:12:01',
                'updated_at' => '2024-01-16 09:12:01',
            ),
            38 => 
            array (
                'id' => 39,
                'user_id' => 1,
                'youtube_id' => 'HqOw-rIXFuw',
                'judul' => 'Kemitraan Saling Menguntungkan antara Petani, Penyedia Saprodi dan Offtaker',
                'tanggal' => '2024-01-17',
                'cover' => 'YJQhHQq3Hd3Vg5CWmjXbtVusRaHu2LvYTbe9hLUJ.jpg',
                'episode' => 1083,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-17 09:23:32',
                'updated_at' => '2024-01-17 09:23:32',
            ),
            39 => 
            array (
                'id' => 40,
                'user_id' => 1,
                'youtube_id' => '9hh6VB3Vl9I',
                'judul' => 'Mengoptimalkan Potensi Lahan Kering',
                'tanggal' => '2024-01-22',
                'cover' => 't9d84kj0DcTkeuGcnec6vNYRquhcQGhJGzlcm6vQ.jpg',
                'episode' => 1085,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-22 09:06:13',
                'updated_at' => '2024-01-22 09:06:13',
            ),
            40 => 
            array (
                'id' => 41,
                'user_id' => 1,
                'youtube_id' => 'tGpmJonXMJM',
                'judul' => 'Kiat Sukses Pelaku Usaha Pangan Lokal',
                'tanggal' => '2024-01-23',
                'cover' => '8SGUrDNSluIuqb8QDQISesuLHTKPLBFQqZUXeb0n.jpg',
                'episode' => 1086,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-23 13:08:30',
                'updated_at' => '2024-01-23 13:08:30',
            ),
            41 => 
            array (
                'id' => 42,
                'user_id' => 1,
                'youtube_id' => 'bu-QHtq9OsA',
                'judul' => 'Strategi Peningkatan Kesejahteraan Petani Singkong',
                'tanggal' => '2024-01-24',
                'cover' => '2Wr21l1d19FYCofw2NzXwX4ucMvP11PRkrXnZdR2.png',
                'episode' => 1087,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-24 10:41:53',
                'updated_at' => '2024-01-24 10:44:12',
            ),
            42 => 
            array (
                'id' => 43,
                'user_id' => 1,
                'youtube_id' => 'ZeO1tTEh9fw',
                'judul' => 'Penguatan Sistem Pangan Nasional Berkelanjutan Berbasis Komoditas Padi dan Pangan Lainnya',
                'tanggal' => '2024-01-25',
                'cover' => 'b1iPFCOVtnvIHxyL1msNQLtqAF3vJg5ygFEzTFnP.jpg',
                'episode' => 1088,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-25 09:08:53',
                'updated_at' => '2024-01-25 09:08:53',
            ),
            43 => 
            array (
                'id' => 44,
                'user_id' => 1,
                'youtube_id' => 'iva4oL9rNi8',
                'judul' => 'Minat Petani dalam Budidaya Kedelai Sesuai SOP',
                'tanggal' => '2024-01-29',
                'cover' => 'kwcm7s8EAbgdAQ7rowYkHmgxcpIk3aiNewWX2XN1.jpg',
                'episode' => 1089,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-29 09:08:54',
                'updated_at' => '2024-01-29 09:08:54',
            ),
            44 => 
            array (
                'id' => 45,
                'user_id' => 1,
                'youtube_id' => 'BHaQfHAxbdo',
                'judul' => 'Produksi Bahan Pangan Organik secara Mandiri',
                'tanggal' => '2024-01-30',
                'cover' => '8y5dtbJD9U0R8kwPzTNFSUNGWp2iNmkCUhe5nbP8.png',
                'episode' => 1090,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-30 05:19:36',
                'updated_at' => '2024-01-30 05:19:36',
            ),
            45 => 
            array (
                'id' => 46,
                'user_id' => 1,
                'youtube_id' => 'JwsNileW1dk',
                'judul' => 'Pertanian Tanaman Pangan di Indonesia dan Jepang',
                'tanggal' => '2024-01-31',
                'cover' => 'ZBI8tZwlRI3U2AYHPee6MDob4UiNGzeT1blWtX5U.jpg',
                'episode' => 1091,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-01-31 09:10:29',
                'updated_at' => '2024-01-31 09:10:29',
            ),
            46 => 
            array (
                'id' => 47,
                'user_id' => 1,
                'youtube_id' => 'L8RX7F7jerE',
                'judul' => 'Pemanfaatan Teknologi Nuklir untuk Pemuliaan Padi dan Sorgum',
                'tanggal' => '2024-02-01',
                'cover' => 'UdEyPjJIHONxXbsFDc6uyRSbPpjOENnG28ycttl1.jpg',
                'episode' => 1092,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-02-01 09:04:35',
                'updated_at' => '2024-02-01 09:04:35',
            ),
            47 => 
            array (
                'id' => 48,
                'user_id' => 1,
                'youtube_id' => '_ODXOnCSAjo',
                'judul' => 'Strategi untuk Petani Meningkatkan Produktivitas dan Produksi Pangan',
                'tanggal' => '2024-02-05',
                'cover' => '9UQKWDtj3UpThvlR88XZbI2mTo9T9tBXFKvZZTaZ.jpg',
                'episode' => 1093,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-02-05 09:03:25',
                'updated_at' => '2024-02-05 09:03:25',
            ),
            48 => 
            array (
                'id' => 49,
                'user_id' => 1,
                'youtube_id' => 'PP86NFGwpDM',
                'judul' => 'Implementasi Hukum Perlindungan Lahan Pertanian Pangan Berkelanjutan',
                'tanggal' => '2024-02-06',
                'cover' => 'lqyJkH1zFcDGoqDqQyKk1mA6VhnntiRm3NzyMDoB.jpg',
                'episode' => 1094,
                'active' => 'yes',
                'status' => 'publish',
                'created_at' => '2024-02-06 09:37:44',
                'updated_at' => '2024-02-06 10:06:02',
            ),
        ));
        
        
    }
}