<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class KomoditasProdusenTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('komoditas_produsen')->delete();
        
        \DB::table('komoditas_produsen')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 11,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'OLAHAN',
                'nama_komoditas' => 'jagung',
                'alamat' => 'Kp Cibodas Desa Sukatani Kecematan Sukatani Kota purwalarta',
                'produksi_kuantitas' => '10 Ton',
                'produksi_waktu' => '12 hari',
                'deskripsi' => 'di jual jagung sebanyak  10 ton hubungi segera',
                'photo' => 'P3Uucn0Znr8XhGRIdcL0VfToJy7bsFHX51azFn5E.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-07 23:00:17',
                'updated_at' => '2023-10-07 23:00:17',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 122,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => NULL,
                'nama_komoditas' => NULL,
                'alamat' => 'Desa Wonorejo',
                'produksi_kuantitas' => '2 Ton',
                'produksi_waktu' => '5 hari',
                'deskripsi' => NULL,
                'photo' => 'yrgzErkBu0S1Tf3v8NXHPkPILRjqvUoAtmgOgS8B.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-09 08:09:37',
                'updated_at' => '2023-10-09 08:09:37',
            ),
            2 => 
            array (
                'id' => 7,
                'user_id' => 1646,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'Beras',
                'alamat' => NULL,
                'produksi_kuantitas' => '1 Ton',
                'produksi_waktu' => '1 hari',
                'deskripsi' => 'Peningkatan produksi',
                'photo' => 'w0J0RdGszBphR5aEAkxZLMbnehvJopQwvCnvizAy.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-09 12:07:25',
                'updated_at' => '2023-10-09 12:07:25',
            ),
            3 => 
            array (
                'id' => 14,
                'user_id' => 13439,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'OLAHAN',
                'nama_komoditas' => 'Beras',
                'alamat' => 'Pagar merbau, Deli Serdang, Sumatera Utara',
                'produksi_kuantitas' => '650 Kg',
                'produksi_waktu' => '6 bulan',
                'deskripsi' => 'Beras mentik susu wangi mempunyai warna beras yang putih dan wangi',
                'photo' => 'dbehXtar87JAlPVRiHVyeDCw74BkVMWkxndInSgf.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-10 10:15:19',
                'updated_at' => '2023-10-10 10:15:19',
            ),
            4 => 
            array (
                'id' => 19,
                'user_id' => 750,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'LAINNYA',
                'nama_komoditas' => NULL,
                'alamat' => 'Sumbersuko kabupaten Lumajang',
                'produksi_kuantitas' => '1500 Kg',
                'produksi_waktu' => '1 hari',
                'deskripsi' => 'Panen kedelai',
                'photo' => 'LRfzckLAEfWLb8Ye6Pvc50aVM43qJZZjve7s9vi6.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-10 14:04:43',
                'updated_at' => '2023-10-10 14:04:43',
            ),
            5 => 
            array (
                'id' => 25,
                'user_id' => 7828,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'UBI KAYU',
                'alamat' => 'DESA PETUNTAWA, KECAMATAN ILE APE, KABUPATEN LEMBATA, NTT',
                'produksi_kuantitas' => '1 Ton',
                'produksi_waktu' => '1 hari',
                'deskripsi' => 'Ubi Kayu, untuk memenuhi kebutuhan komsumsi sendiri dan Pakan Ternak',
                'photo' => '8bkTlpGuFo0bxsiFOdmlDvaxfiBb19ok8j9pVYnK.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-11 10:34:11',
                'updated_at' => '2023-10-11 10:34:11',
            ),
            6 => 
            array (
                'id' => 28,
                'user_id' => 14556,
                'jenis_komoditas' => 'HORTIKULTURA',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'Cabai',
                'alamat' => 'Mojotengah,Wonosobo',
                'produksi_kuantitas' => '50 Kg',
                'produksi_waktu' => '5 hari',
                'deskripsi' => 'Cabai rawit merah',
                'photo' => 'sPV95UNUaO2LzNfegnosBArdvdUuywICzUsx8Bvv.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-11 12:40:26',
                'updated_at' => '2023-10-11 12:40:26',
            ),
            7 => 
            array (
                'id' => 29,
                'user_id' => 14578,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'LAINNYA',
                'nama_komoditas' => 'Kelor',
                'alamat' => 'Kunduran, Kab. Blora, Jawa Tengah',
                'produksi_kuantitas' => '10 Ton',
                'produksi_waktu' => '1 bulan',
                'deskripsi' => 'Mengolah hasil panen daun Kelor menjadi berbagai macam variasi produk, diantaranya Pangan, Obat Tradisional dan Kosmetik',
                'photo' => 'jcYxC7l8NBusp1WTsgpMJajkLh1s4ozWLQYz1BeR.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-12 09:42:27',
                'updated_at' => '2023-10-12 09:42:27',
            ),
            8 => 
            array (
                'id' => 51,
                'user_id' => 15607,
                'jenis_komoditas' => 'HORTIKULTURA',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'jamur tiram',
                'alamat' => 'Lueng Bata ,Kita Banda Aceh',
                'produksi_kuantitas' => '10 Kg',
                'produksi_waktu' => '1 hari',
                'deskripsi' => 'Budidaya jamur tiram',
                'photo' => 'RWe0tcbAy9bh18nDC2hCWRcbVcatVPjH29E3vmbo.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-19 13:16:39',
                'updated_at' => '2023-10-19 13:16:39',
            ),
            9 => 
            array (
                'id' => 53,
                'user_id' => 15756,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'Benih Padi dan kacang hijau',
                'alamat' => 'Ds. Rajek RT.001/002 Kec. Godong Kab. Grobogan 58162',
                'produksi_kuantitas' => '1 Ton',
                'produksi_waktu' => '1 bulan',
                'deskripsi' => 'Produksi benih padi dan kacang hijau berkualitas',
                'photo' => 'HRSKOPplvsvHBnkvgPzYm160y4sQehA461kl7Pms.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-19 14:01:33',
                'updated_at' => '2023-10-19 14:01:33',
            ),
            10 => 
            array (
                'id' => 54,
                'user_id' => 4819,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'LAINNYA',
                'nama_komoditas' => 'Benih Tanaman Pangan',
                'alamat' => 'Kabupaten Bogor',
                'produksi_kuantitas' => '72 Ton',
                'produksi_waktu' => '12 bulan',
                'deskripsi' => 'Produksi benih padi unggul bersertifikat',
                'photo' => 'F4dtAxjBBcCgi1bG3pySkd9ct2g5He2g7KDxutkr.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-19 14:09:25',
                'updated_at' => '2023-10-19 14:09:25',
            ),
            11 => 
            array (
                'id' => 67,
                'user_id' => 16223,
                'jenis_komoditas' => 'PETERNAKAN',
                'kategori_komoditas' => 'OLAHAN',
                'nama_komoditas' => 'Susu kambing pasturisasi',
                'alamat' => 'Desa Dlemer Arosbaya',
                'produksi_kuantitas' => '200 Unit',
                'produksi_waktu' => '1 hari',
            'deskripsi' => 'Susu kambing pasturisasi merek (SAPEROS)',
                'photo' => '29TySIBhBTRjQksXPzXnMKHMRxDikklY3beKUuyQ.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-23 21:43:48',
                'updated_at' => '2023-10-23 21:43:48',
            ),
            12 => 
            array (
                'id' => 68,
                'user_id' => 16223,
                'jenis_komoditas' => 'SARANA PRODUKSI',
                'kategori_komoditas' => 'BIBIT',
                'nama_komoditas' => 'Cempe kambing Sapera dan Saperos',
                'alamat' => 'Desa Dlemer Arosbaya',
                'produksi_kuantitas' => '330 Ekor',
                'produksi_waktu' => '24 bulan',
                'deskripsi' => 'Anakan kambing sapera dan saperos menjadi bibit kambing perah yang unggul untuk di kembangkan di indonesia sebagai peng hasil susu yang cocok dengan iklim tropis indonesia.',
                'photo' => 'wfxuhrnLd7pimvrE7zdhfUUI1FFMjS7NcjooHkSg.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-23 21:50:26',
                'updated_at' => '2023-10-23 21:50:26',
            ),
            13 => 
            array (
                'id' => 71,
                'user_id' => 16563,
                'jenis_komoditas' => 'SARANA PRODUKSI',
                'kategori_komoditas' => 'PUPUK',
                'nama_komoditas' => 'Kompos Kambing Fermentasi, Media Tanam, Sekam Bakar, Nutrisi Tanaman Cair',
                'alamat' => 'Desa Tladan, Kecamatan Kawedanan, Kabupaten Magetan',
                'produksi_kuantitas' => '4 Ton',
                'produksi_waktu' => '1 bulan',
                'deskripsi' => 'Produksi Pupuk kompos kambing fermentasi dengan tekstur sudah halus.',
                'photo' => 'Bx2aOpzPByUriIhOnaG8LBI1izp9hymQ9xoZESRM.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-25 08:38:54',
                'updated_at' => '2023-10-25 08:38:54',
            ),
            14 => 
            array (
                'id' => 76,
                'user_id' => 15756,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'Benih Padi VUB',
                'alamat' => 'Dsn. Rajek RT.001/002 Ds. Rajek Kec. Godong Kab. Grobogan - Jawa Tengah',
                'produksi_kuantitas' => '1 Ton',
                'produksi_waktu' => '1 bulan',
                'deskripsi' => 'Benih Padi Inbrida Varietas Unggul Baru bersertifikat, dibawah pengawasan BPSB provinsi Jawa Tengah',
                'photo' => 'zHodoivjObA9QL2yFNXTxgiA3hmm86KLSZIJHFdu.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-26 10:27:27',
                'updated_at' => '2023-10-26 10:27:27',
            ),
            15 => 
            array (
                'id' => 77,
                'user_id' => 5360,
                'jenis_komoditas' => 'SARANA PRODUKSI',
                'kategori_komoditas' => 'BIBIT',
                'nama_komoditas' => 'Pupuk kompos, media tanam,pupuk kandang',
                'alamat' => 'Gandasari Cikarang barat kabupaten Bekasi',
                'produksi_kuantitas' => '100 Kg',
                'produksi_waktu' => '1 hari',
                'deskripsi' => 'Pupuk kompos super
Dari kotoran hewan sapi di proses secara langsung dengan kandungan
Berbagai unsur hara yang dibutuhkan tanaman',
                'photo' => 'QyaGsQzjAMdKLhfFUV9LJKSUPQpqWwwH70hvwtjq.jpg',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-29 07:41:30',
                'updated_at' => '2023-10-29 07:41:30',
            ),
            16 => 
            array (
                'id' => 81,
                'user_id' => 10229,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'BENIH JAGUNG HIBRIDA MERK KANAKA',
                'alamat' => 'Dukuh, Maron, Selokajang, Kec. Srengat, Kabupaten Blitar, Jawa Timur',
                'produksi_kuantitas' => '40 Ton',
                'produksi_waktu' => '1 bulan',
                'deskripsi' => 'BENIH JAGUNG HIBRIDA merk dagang KANAKA
varietas HJ21 dan JH45
Hub : 0811 3655 622 atau 081 136 5552

Berdaya Adaptasi Luas
Tahan Bulai dan penyakit Jagung Lainnya
Rendemen dan Produktivitas Tinggi
Umur Genjah
Biji Rapat, menancap dalam dan Warna lebih Cerah',
                'photo' => 'ztBJiaeu1W6GGzv6ERZjTTxCYpdBFHdpjOu1JD5a.png',
                'propinsi' => NULL,
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-10-31 10:57:41',
                'updated_at' => '2023-10-31 10:57:41',
            ),
            17 => 
            array (
                'id' => 89,
                'user_id' => 12,
                'jenis_komoditas' => 'HORTIKULTURA',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'Oyong Gambas',
                'alamat' => 'Ciranji',
                'produksi_kuantitas' => '1 Ton',
                'produksi_waktu' => '10 hari',
            'deskripsi' => 'oyong gambas kualitas unggul, langsung panen dari lahan. stok setiap saat ready. biasa suply pasar Induk Subang. Harga 8000/kg (belum Ongkir)',
                'photo' => 'UevVMilPqKDIzpidWm2d6q8ugtMilhkjnNsoBGtW.jpg',
                'propinsi' => 'Jawa Barat',
                'kota' => 'Kabupaten Purwakarta',
                'status' => 1,
                'created_at' => '2023-11-08 15:26:22',
                'updated_at' => '2023-11-08 15:26:22',
            ),
            18 => 
            array (
                'id' => 90,
                'user_id' => 214,
                'jenis_komoditas' => 'HORTIKULTURA',
                'kategori_komoditas' => 'OLAHAN',
                'nama_komoditas' => 'JAHE MERAH INSTAN',
                'alamat' => 'DUSUN KALIPUTIH DESA POLOSIRI KECAMATAN BAWEN',
                'produksi_kuantitas' => '170 Kg',
                'produksi_waktu' => '1 bulan',
                'deskripsi' => 'Minuman herbal jahe merah merk Juston sudah berbentuk serbuk instan yg siap seduh. sudah manis tanpa mencampur gula lagi, dengan kemasan Standing Pouch Full alumunium Foil dgn Netto 170 gr/ 1kemasan. bisa untuk 7 gelas blimbing. 
Tanpa Pemanis buatan. Tanpa pengawet dan Tanpa pewarna buatan.. terbuat dr bahan herbal..Rasa rempah2 nya nendang bgt pokonya.. Yuukk cobain....',
                'photo' => '3OWhrzZjdNcr5u9oyxu32yH7iGF1g12h4PhvmK5v.jpg',
                'propinsi' => 'Jawa Tengah',
                'kota' => 'Kabupaten Semarang',
                'status' => 1,
                'created_at' => '2023-11-13 09:58:08',
                'updated_at' => '2023-11-13 09:58:08',
            ),
            19 => 
            array (
                'id' => 91,
                'user_id' => 214,
                'jenis_komoditas' => 'HORTIKULTURA',
                'kategori_komoditas' => 'OLAHAN',
                'nama_komoditas' => 'WEDANG UWUH INSTAN',
                'alamat' => 'DUSUN KALIPUTIH DESA POLOSIRI KECAMATAN BAWEN',
                'produksi_kuantitas' => '170 Kg',
                'produksi_waktu' => '1 bulan',
                'deskripsi' => 'Wedang Uwuh Instan adalah minuman serbuk instan yg siap seduh sudah manis. tanpa mencampur gula lagi. terbuat dr bahan alami. tidak pakai bahan pengawet, tanpa pemanis buatan alias gula asli. dan tanpa pewarna buatan.. 1 kemasan 170 gr  bisa buat 7 gelas. yukk rasakan sensasi rempahnya....',
                'photo' => 'GLiBpTzmIHL5Nl9z3ZRijO5NEBmye1h3doDVy1dp.jpg',
                'propinsi' => 'Jawa Tengah',
                'kota' => 'Kabupaten Semarang',
                'status' => 1,
                'created_at' => '2023-11-13 10:04:31',
                'updated_at' => '2023-11-13 10:04:31',
            ),
            20 => 
            array (
                'id' => 95,
                'user_id' => 214,
                'jenis_komoditas' => 'HORTIKULTURA',
                'kategori_komoditas' => 'OLAHAN',
                'nama_komoditas' => 'KUNYIT INSTAN',
                'alamat' => 'Dsn KALIPUTIH DESA POLOSIRI KECAMATAN BAWEN KAB. SEMARANG',
                'produksi_kuantitas' => '50 Ton',
                'produksi_waktu' => '1 hari',
                'deskripsi' => 'Minuman serbuk instan yang siap seduh, sdh manis tanpa mencampur gula lagi.. terbuat dr bahan-bahan alami, tanpa pengawet, tanpa pewarna dan tanpa pemanis buatan. yang bermasalah dgn haid yg terasa sakit.. rekomended banget minum kunyit instan Wa me : 085870483550',
                'photo' => 'HHR63ezjErlW8pGpR3NCZdN3CyNJHleJLiF3n04V.jpg',
                'propinsi' => 'Jawa Tengah',
                'kota' => 'Kabupaten Semarang',
                'status' => 1,
                'created_at' => '2023-11-15 10:27:43',
                'updated_at' => '2023-11-15 10:27:43',
            ),
            21 => 
            array (
                'id' => 96,
                'user_id' => 418,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'OLAHAN',
                'nama_komoditas' => 'Ubi jalar',
                'alamat' => 'Padang kaduduak',
                'produksi_kuantitas' => '1 Kg',
                'produksi_waktu' => '1 hari',
                'deskripsi' => 'Kripik Ubi Jalar',
                'photo' => 'Q7VIwUsXD90DCiI9gkepjderLgVJ5lQvHtHycV9n.jpg',
                'propinsi' => 'Sumatera Barat',
                'kota' => 'Kota Payakumbuh',
                'status' => 1,
                'created_at' => '2023-11-28 09:34:37',
                'updated_at' => '2023-11-28 09:34:37',
            ),
            22 => 
            array (
                'id' => 101,
                'user_id' => 22406,
                'jenis_komoditas' => 'HORTIKULTURA',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'Seledri',
                'alamat' => 'Desa Patongloan, Kecamatan Baroko',
                'produksi_kuantitas' => '50 Kg',
                'produksi_waktu' => '7 hari',
            'deskripsi' => 'Seledri dipanen seminggu sekali dengan hasil sekitar 200 ikat (±50kg)',
                'photo' => 'VhJVCKxoyk0J9BGyp0Qa9DwteQpcEnDAuDubRo2n.jpg',
                'propinsi' => 'Sulawesi Selatan',
                'kota' => 'Enrekang',
                'status' => 1,
                'created_at' => '2023-12-06 22:52:21',
                'updated_at' => '2023-12-06 22:52:21',
            ),
            23 => 
            array (
                'id' => 102,
                'user_id' => 18063,
                'jenis_komoditas' => 'HORTIKULTURA',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'Aneka ragam cabe dan sayuran',
                'alamat' => 'Desa lalang Kabung kec. Pelalawan',
                'produksi_kuantitas' => '200 Kg',
                'produksi_waktu' => '1 hari',
                'deskripsi' => 'Penanaman cabe merah dan cabe putih',
                'photo' => 'Bkm3dIwfAVMDgMAGCbwcSdWs3kEpqrkon7rotmgx.jpg',
                'propinsi' => 'Riau',
                'kota' => 'Pelalawan',
                'status' => 1,
                'created_at' => '2023-12-12 12:43:39',
                'updated_at' => '2023-12-12 12:43:39',
            ),
            24 => 
            array (
                'id' => 103,
                'user_id' => 18063,
                'jenis_komoditas' => 'HORTIKULTURA',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'Aneka ragam cabe dan sayuran',
                'alamat' => 'Desa lubuk Ogung kec. Pelalawan',
                'produksi_kuantitas' => '200 Kg',
                'produksi_waktu' => '1 hari',
                'deskripsi' => 'Penanaman cabe merah dan cabe putih',
                'photo' => 'z97WDoAFZcZSrAisVuyncQ6oNyZIy4xwlGKMW9F9.jpg',
                'propinsi' => 'Riau',
                'kota' => 'Pelalawan',
                'status' => 1,
                'created_at' => '2023-12-12 12:48:07',
                'updated_at' => '2023-12-12 12:48:07',
            ),
            25 => 
            array (
                'id' => 104,
                'user_id' => 18063,
                'jenis_komoditas' => 'HORTIKULTURA',
                'kategori_komoditas' => NULL,
                'nama_komoditas' => 'Aneka ragam cabe dan sayuran',
                'alamat' => 'Desa lubuk Ogung kec. Pelalawan',
                'produksi_kuantitas' => '200 Kg',
                'produksi_waktu' => '1 hari',
                'deskripsi' => 'Penanaman cabe merah dan cabe putih',
                'photo' => 'XbaLaocXdCuW8YqZ1dQJFY2L9pwQgpOjZPeaNUlg.jpg',
                'propinsi' => 'Riau',
                'kota' => NULL,
                'status' => 1,
                'created_at' => '2023-12-12 12:48:44',
                'updated_at' => '2023-12-12 12:48:44',
            ),
            26 => 
            array (
                'id' => 105,
                'user_id' => 23841,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'OLAHAN',
                'nama_komoditas' => 'Herbal, rempah',
                'alamat' => 'jl. P.Batam no.39 Tabanan Bali',
                'produksi_kuantitas' => '1 Kg',
                'produksi_waktu' => '1 hari',
                'deskripsi' => 'Produk herbal; simplisia, powder, minyak, teh, rempah',
                'photo' => 'ucp7LXGr6G0c5bMYACgjPbeQPIopKoPfJYtIalQU.jpg',
                'propinsi' => 'Bali',
                'kota' => 'Kabupaten Tabanan',
                'status' => 1,
                'created_at' => '2023-12-19 15:00:57',
                'updated_at' => '2023-12-19 15:00:57',
            ),
            27 => 
            array (
                'id' => 109,
                'user_id' => 27537,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'Padi dan Beras Organik',
                'alamat' => 'Desa krasak kec. Jatibarang kab. Indramayu',
                'produksi_kuantitas' => '1000 Ton',
                'produksi_waktu' => '12 bulan',
                'deskripsi' => 'Padi dan Beras Organik',
                'photo' => 'TgvFyesbQgfLMqHtPOJVCJ4xBYCOI3ceAWH7z0TU.jpg',
                'propinsi' => 'Jawa Barat',
                'kota' => 'Kabupaten Indramayu',
                'status' => 1,
                'created_at' => '2024-01-17 10:33:47',
                'updated_at' => '2024-01-17 10:33:47',
            ),
            28 => 
            array (
                'id' => 110,
                'user_id' => 3200,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'LAINNYA',
                'nama_komoditas' => 'Benih pertanian',
                'alamat' => 'Ds jimbe kec jenangan',
                'produksi_kuantitas' => '1 Ton',
                'produksi_waktu' => '1 hari',
                'deskripsi' => NULL,
                'photo' => 'TJpWswzoJwN7mgXTiprY09Uh1ap0WHk5ZjyFJtm7.jpg',
                'propinsi' => 'Jawa Timur',
                'kota' => 'Kabupaten Ponorogo',
                'status' => 1,
                'created_at' => '2024-01-22 11:54:00',
                'updated_at' => '2024-01-22 11:54:00',
            ),
            29 => 
            array (
                'id' => 116,
                'user_id' => 17298,
                'jenis_komoditas' => 'PERKEBUNAN',
                'kategori_komoditas' => 'OLAHAN',
                'nama_komoditas' => 'Serbuk jahe instan cap JEMPOL',
                'alamat' => 'BOROBUDUR',
                'produksi_kuantitas' => '10 Kg',
                'produksi_waktu' => '1 bulan',
                'deskripsi' => 'Serbuk jahe instan yang diolah dari jahe segar dengan bahan tambahan kapulaga,serai,kayumanis dan gula',
                'photo' => '9E1rbrJpMv48ZFvjr1iyG2Sju1Ve9ZuMaCBKhZkJ.jpg',
                'propinsi' => 'Jawa Tengah',
                'kota' => 'Kabupaten Magelang',
                'status' => 1,
                'created_at' => '2024-01-25 11:18:22',
                'updated_at' => '2024-01-25 11:18:22',
            ),
            30 => 
            array (
                'id' => 117,
                'user_id' => 29655,
                'jenis_komoditas' => 'SARANA PRODUKSI',
                'kategori_komoditas' => 'PUPUK',
                'nama_komoditas' => 'Pupuk Alami KUPULA',
                'alamat' => 'Desa Meuria Paloh Kec Muara Satu',
                'produksi_kuantitas' => '3 Ton',
                'produksi_waktu' => '1 hari',
                'deskripsi' => 'PUPUK ORGANIK KUPULA        
Pupuk Organik KUPULA Adalah Suatu Proses Permentasi Kotoran Hewan ( KOHE ) Yang Di Campur Dengan Beberapa Bahan Organik Lainnya, Sehingga Dapat Di Gunakan Untuk Memperbaiki Ekosistem Tanah Dan Memicu Munculnya MIKRO ORGANISME alam Tanah, Sehingga Dapat Menyuburkan Tanah Dan  Mempercepat Pertumbuhan Tanaman Serta Tahan Terhadap Serangan Hama

Pupuk Organik KUPULA Di Produksi Oleh Anak Negeri, Dari Berbagai Bahan – Bahan Organik Yang Terpilih Dan  Ramah Lingkungan, Yang Di Kombinasi  Dengan MIKROBA Unggul Sehingga Sangat Menguntungkan Bagi Pertumbuhan Tanaman Serta Menjadikan Tanaman ALAMI, Yang Di perkaya Dengan Unsur Hara Mirko Maupun Makro Yang Berimbang Membuat Berbagai Farian Tanaman  Tumbuh Subur dan Tahan Terhadap Penyakit',
                'photo' => 'OhwwRvVK0UtKPnTYEOI9TDGRvumUMJ7mJpa9iIXb.jpg',
                'propinsi' => 'Nanggroe Aceh Darussalam',
                'kota' => 'Kota Lhokseumawe',
                'status' => 1,
                'created_at' => '2024-01-30 10:42:44',
                'updated_at' => '2024-01-30 10:42:44',
            ),
            31 => 
            array (
                'id' => 118,
                'user_id' => 11,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'padi',
                'alamat' => 'lewi liang',
                'produksi_kuantitas' => '1 Ton',
                'produksi_waktu' => '3 hari',
                'deskripsi' => 'padi varietas inpari',
                'photo' => 'sSY3qAIUtga8OGrFWmFEsBG3a3A5PY9TLjy7JdEd.jpg',
                'propinsi' => 'Jawa Barat',
                'kota' => 'Kabupaten Bogor',
                'status' => 1,
                'created_at' => '2024-02-01 15:39:44',
                'updated_at' => '2024-02-01 15:39:44',
            ),
            32 => 
            array (
                'id' => 119,
                'user_id' => 11,
                'jenis_komoditas' => 'HORTIKULTURA',
                'kategori_komoditas' => 'SEGAR',
                'nama_komoditas' => 'oyong',
                'alamat' => 'campaka',
                'produksi_kuantitas' => '2 Ton',
                'produksi_waktu' => '8 hari',
                'deskripsi' => 'oyong super',
                'photo' => 'VmrElxx3NHa5hh6dU1dzNLBeEXyTujXvsCrwABTO.png',
                'propinsi' => 'Jawa Barat',
                'kota' => 'Kabupaten Purwakarta',
                'status' => 1,
                'created_at' => '2024-02-01 15:41:55',
                'updated_at' => '2024-02-01 15:41:55',
            ),
            33 => 
            array (
                'id' => 120,
                'user_id' => 3200,
                'jenis_komoditas' => 'TANAMAN PANGAN',
                'kategori_komoditas' => 'LAINNYA',
                'nama_komoditas' => 'Benih padi',
                'alamat' => 'Jimbe jenangan',
                'produksi_kuantitas' => '5 Ton',
                'produksi_waktu' => '1 hari',
                'deskripsi' => NULL,
                'photo' => 'Q4P44oKjdBAh55onAuiyKzYQmvcrdcuieOVo21NC.jpg',
                'propinsi' => 'Jawa Timur',
                'kota' => 'Kabupaten Ponorogo',
                'status' => 1,
                'created_at' => '2024-02-05 14:54:32',
                'updated_at' => '2024-02-05 14:54:32',
            ),
        ));
        
        
    }
}