version: '3.8'
services:
  db:
    image: mysql:5.7.22
    platform: linux/amd64
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql_db_data:/var/lib/mysql
    networks:
      - app-network

  webserver:
    image: nginx:latest
    platform: linux/amd64
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_db_data:
